syntax = "proto2";

package remotemessage;

option java_package = "com.google.android.apps.tv.remote.protocol";
option java_outer_classname = "RemoteProto";

enum Direction {
    UNKNOWN_DIRECTION = 0;
    SHORT = 1;
    START_LONG = 2;
    END_LONG = 3;
}

message RemoteConfigure {
    optional int32 code1 = 1;
    optional DeviceInfo device_info = 2;
}

message DeviceInfo {
    optional string model = 1;
    optional string vendor = 2;
    optional int32 unknown1 = 3;
    optional string unknown2 = 4;
    optional string package_name = 5;
    optional string app_version = 6;
}

message RemoteSetActive {
    optional int32 active = 1;
}

message RemotePingRequest {
    optional int32 val1 = 1;
    optional int32 val2 = 2;
}

message RemotePong {
    optional int32 val1 = 1;
}

message RemoteKeyInject {
    optional int32 key_code = 1;
    optional Direction direction = 2;
}

message RemoteImeKeyInject {
    optional int32 app_info = 1;
    optional string text = 2;
}

message RemoteImeBatchEdit {
    optional int32 app_info = 1;
    optional int32 counter = 2;
    optional string field_id = 3;
    optional string text = 4;
}

message RemoteMessage {
    optional RemoteConfigure remote_configure = 1;
    optional RemoteSetActive remote_set_active = 2;
    optional RemotePingRequest remote_ping_request = 3;
    optional RemotePong remote_pong = 4;
    optional RemoteKeyInject remote_key_inject = 5;
    optional RemoteImeKeyInject remote_ime_key_inject = 6;
    optional RemoteImeBatchEdit remote_ime_batch_edit = 7;
}
